# Generated by Django 6.0.3 on 2026-03-26 20:37

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(blank=True, max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('track_number', models.CharField(blank=True, default=apps.orders.models.generate_track, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
