# Generated by Django 6.0.3 on 2026-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_method_alter_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
