# Generated by Django 6.0.3 on 2026-03-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_price_alter_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='theme',
        ),
    ]
