# Generated by Django 6.0.3 on 2026-03-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='excluded_tags',
        ),
        migrations.RemoveField(
            model_name='category',
            name='included_tags',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
